// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: tree_structure.proto

package tsproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 树结构头
type TreeHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	C []*TB `protobuf:"bytes,1,rep,name=C,proto3" json:"C,omitempty"` // 子结构
}

func (x *TreeHeader) Reset() {
	*x = TreeHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tree_structure_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TreeHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeHeader) ProtoMessage() {}

func (x *TreeHeader) ProtoReflect() protoreflect.Message {
	mi := &file_tree_structure_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeHeader.ProtoReflect.Descriptor instead.
func (*TreeHeader) Descriptor() ([]byte, []int) {
	return file_tree_structure_proto_rawDescGZIP(), []int{0}
}

func (x *TreeHeader) GetC() []*TB {
	if x != nil {
		return x.C
	}
	return nil
}

// 树结构体
type TB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	B string `protobuf:"bytes,1,opt,name=B,proto3" json:"B,omitempty"` // 值
	C []*TB  `protobuf:"bytes,2,rep,name=C,proto3" json:"C,omitempty"` // 子结构
}

func (x *TB) Reset() {
	*x = TB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tree_structure_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TB) ProtoMessage() {}

func (x *TB) ProtoReflect() protoreflect.Message {
	mi := &file_tree_structure_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TB.ProtoReflect.Descriptor instead.
func (*TB) Descriptor() ([]byte, []int) {
	return file_tree_structure_proto_rawDescGZIP(), []int{1}
}

func (x *TB) GetB() string {
	if x != nil {
		return x.B
	}
	return ""
}

func (x *TB) GetC() []*TB {
	if x != nil {
		return x.C
	}
	return nil
}

var File_tree_structure_proto protoreflect.FileDescriptor

var file_tree_structure_proto_rawDesc = []byte{
	0x0a, 0x14, 0x74, 0x72, 0x65, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a,
	0x0a, 0x54, 0x72, 0x65, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x01, 0x43,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54,
	0x42, 0x52, 0x01, 0x43, 0x22, 0x2b, 0x0a, 0x02, 0x54, 0x42, 0x12, 0x0c, 0x0a, 0x01, 0x42, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x42, 0x12, 0x17, 0x0a, 0x01, 0x43, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x42, 0x52, 0x01,
	0x43, 0x42, 0x13, 0x5a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x74,
	0x73, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tree_structure_proto_rawDescOnce sync.Once
	file_tree_structure_proto_rawDescData = file_tree_structure_proto_rawDesc
)

func file_tree_structure_proto_rawDescGZIP() []byte {
	file_tree_structure_proto_rawDescOnce.Do(func() {
		file_tree_structure_proto_rawDescData = protoimpl.X.CompressGZIP(file_tree_structure_proto_rawDescData)
	})
	return file_tree_structure_proto_rawDescData
}

var file_tree_structure_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tree_structure_proto_goTypes = []interface{}{
	(*TreeHeader)(nil), // 0: proto.TreeHeader
	(*TB)(nil),         // 1: proto.TB
}
var file_tree_structure_proto_depIdxs = []int32{
	1, // 0: proto.TreeHeader.C:type_name -> proto.TB
	1, // 1: proto.TB.C:type_name -> proto.TB
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tree_structure_proto_init() }
func file_tree_structure_proto_init() {
	if File_tree_structure_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tree_structure_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TreeHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tree_structure_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tree_structure_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tree_structure_proto_goTypes,
		DependencyIndexes: file_tree_structure_proto_depIdxs,
		MessageInfos:      file_tree_structure_proto_msgTypes,
	}.Build()
	File_tree_structure_proto = out.File
	file_tree_structure_proto_rawDesc = nil
	file_tree_structure_proto_goTypes = nil
	file_tree_structure_proto_depIdxs = nil
}
